# site settings
title: Back Matter 
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: Back Matter is a print and digital magazine produced by graduate students in the Creative Publishing and Critical Journalism program at The New School for Social Research. By examining  New York City's publishing industry and asking how work is produced and by whom, we hope to better understand how media drives, reflects, and follows culture. Accelerating developments in technology force us to ask: what will publishing be and what is it now?
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
